version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
        # When the PostgreSQL container is started it will run any scripts
        # provided in the `docker-entrypoint-initdb.d` directory, this connects
        # our seed file to that directory so that it gets run
        # - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
volumes:
  db-data:
